# Generated by Django 5.2.7 on 2025-10-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Pagne Boutique",
                        max_length=120,
                        verbose_name="Nom de la boutique",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="La sélection de pagnes qui font la différence",
                        max_length=160,
                        verbose_name="Slogan",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="Niamey, Niger",
                        max_length=200,
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="+227 xx xx xx xx",
                        max_length=40,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="WhatsApp (numéro au format international, ex: 227xxxxxxxx)",
                    ),
                ),
                (
                    "hours",
                    models.CharField(
                        blank=True,
                        default="Lun–Sam 9h–19h",
                        max_length=120,
                        verbose_name="Horaires",
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, default="", verbose_name="Lien Instagram"
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglages boutique",
                "verbose_name_plural": "Réglages boutique",
            },
        ),
    ]
