# Generated by Django 5.2.7 on 2025-10-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_businesssetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssetting",
            name="name",
            field=models.CharField(
                default="ABH – Compagny",
                max_length=120,
                verbose_name="Nom de la boutique",
            ),
        ),
    ]
