# Generated by Django 5.2.7 on 2025-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_businesssetting_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssetting",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
    ]
