# Generated by Django 5.2.7 on 2025-10-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_businesssetting_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssetting",
            name="domain",
            field=models.CharField(
                blank=True,
                help_text="Ex: boutique-amina.com ou amina.localhost",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="businesssetting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
