# Generated by Django 5.2.7 on 2025-10-21 16:48

from django.db import migrations


def forwards(apps, schema_editor):
    BusinessSetting = apps.get_model("catalog", "BusinessSetting")

    # Récupère les domaines déjà non-nuls pour garantir l'unicité
    existing = set(
        BusinessSetting.objects.exclude(domain__isnull=True)
        .exclude(domain__exact="")
        .values_list("domain", flat=True)
    )

    # Politique: si vide -> "localhost", ou "localhost-2", "localhost-3", ...
    base = "localhost"

    for bs in BusinessSetting.objects.all():
        if not bs.domain:
            candidate = base
            i = 1
            while candidate in existing:
                i += 1
                candidate = f"{base}-{i}"
            bs.domain = candidate
            bs.save(update_fields=["domain"])
            existing.add(candidate)


def backwards(apps, schema_editor):
    # On ne remet pas à NULL (no-op)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_businesssetting_domain_businesssetting_is_active"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
