# Generated by Django 5.2.7 on 2025-10-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_populate_businesssetting_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssetting",
            name="domain",
            field=models.CharField(
                default="localhost",
                help_text="Ex: boutique-amina.com ou amina.localhost",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
